apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: grafana-lug
  namespace: monitoring
  labels:
    k8s-app: grafana
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    k8s-app: grafana
  type: NodePort