apiVersion: v1
kind: Namespace
metadata:
  name: netology
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lug-app
  namespace: netology
  labels:
    k8s-app: lug-app
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: lug-app
  template:
    metadata:
      name: lug-app
      labels:
        k8s-app: lug-app
    spec:
      containers:
      - name: lug-nginx
        image: cr.yandex/crpjtbfk7rh581pgd1hk/my-registry:main
        imagePullPolicy: IfNotPresent
        
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lug
  namespace: netology
  labels:
    k8s-app: lug-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    k8s-app: lug-app
  type: NodePort